/*
CONSRAINTS
*/

--While Creating Table
-- NOT NULL
CREATE TABLE EMP
(
EMPID INT NOT NULL,
EMPName VARCHAR(100)
)

INSERT INTO EMP(EMPID,EMPName)
VALUES(1,'Abhilash')
INSERT INTO EMP(EMPID,EMPName)
VALUES(NULL,'AbhiDunnisha')
INSERT INTO EMP(EMPName)
VALUES('Ravindra')

--UNIQUE
DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT UNIQUE,
EMPName VARCHAR(100) 
)


INSERT INTO EMP(EMPID,EMPName)
VALUES(1,'Abhilash')
INSERT INTO EMP(EMPID,EMPName)
VALUES(NULL,'AbhiDunnisha')
INSERT INTO EMP(EMPName)
VALUES('Ravindra')

INSERT INTO EMP(EMPID,EMPName)
VALUES(1,'Abhilash')


SELECT * FROM EMP

---PRIMARY KEY

DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT PRIMARY KEY,
EMPName VARCHAR(100) UNIQUE
)

INSERT INTO EMP(EMPID,EMPName)
VALUES(1,'Abhilash')
INSERT INTO EMP(EMPID,EMPName)
VALUES(NULL,'AbhiDunnisha')
INSERT INTO EMP(EMPName)
VALUES('Ravindra')

INSERT INTO EMP(EMPID,EMPName)
VALUES(1,'Abhilash')

--CHECK
DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT PRIMARY KEY,
EMPName VARCHAR(100) UNIQUE,
Salary MONEY CHECK (Salary>=5000)
)
INSERT INTO EMP(EMPID,EMPName,Salary)
VALUES(1,'Abhilash',6000)
INSERT INTO EMP(EMPID,EMPName,Salary)
VALUES(2,'Ravindra',6500)
INSERT INTO EMP(EMPID,EMPName,Salary)
VALUES(3,'Narendra',4500)

--DEFAULT
DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT PRIMARY KEY,
EMPName VARCHAR(100) UNIQUE,
Salary MONEY CHECK (Salary>=5000),
InsertedDatetime DATETIME DEFAULT GETDATE()
)

INSERT INTO EMP(EMPID,EMPName,Salary,InsertedDatetime)
VALUES(1,'Abhilash',6000,'2023-06-22')
INSERT INTO EMP(EMPID,EMPName,Salary,InsertedDatetime)
VALUES(2,'Ravindra',6500,NULL)
INSERT INTO EMP(EMPID,EMPName,Salary)
VALUES(3,'Narendra',5500)

SELECT * FROM EMP

--IDENTITY
DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT IDENTITY(1,1),
EMPName VARCHAR(100) UNIQUE,
Salary MONEY CHECK (Salary>=5000),
InsertedDatetime DATETIME DEFAULT GETDATE()
)

SP_HELP 'EMP'


INSERT INTO EMP(EMPName,Salary,InsertedDatetime)
VALUES('Abhilash',6000,'2023-06-22')
INSERT INTO EMP(EMPName,Salary,InsertedDatetime)
VALUES('Ravindra',6500,NULL)
INSERT INTO EMP(EMPName,Salary)
VALUES('Narendra',5500)

SELECT * FROM EMP


DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT IDENTITY(1,10),
EMPName VARCHAR(100) UNIQUE,
Salary MONEY CHECK (Salary>=5000),
InsertedDatetime DATETIME DEFAULT GETDATE()
)
INSERT INTO EMP(EMPName,Salary,InsertedDatetime)
VALUES('Abhilash',6000,'2023-06-22')
INSERT INTO EMP(EMPName,Salary,InsertedDatetime)
VALUES('Ravindra',6500,NULL)
INSERT INTO EMP(EMPName,Salary)
VALUES('Narendra',5500)

SELECT * FROM EMP

INSERT INTO EMP(EMPID,EMPName,Salary,InsertedDatetime)
VALUES(41,'Kezia',6000,'2023-06-24')

SET IDENTITY_INSERT EMP ON
INSERT INTO EMP(EMPID,EMPName,Salary,InsertedDatetime)
VALUES(41,'Kezia',6000,'2023-06-24')
SET IDENTITY_INSERT EMP OFF


--FOREIG KEY (Referential Integrity)

CREATE TABLE Department
(
DepartmentID INT IDENTITY(1,1) PRIMARY KEY,
DeptNmae VARCHAR(50)
)

DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT IDENTITY(1,10),
EMPName VARCHAR(100) UNIQUE,
Salary MONEY CHECK (Salary>=5000),
DepTID INT,
InsertedDatetime DATETIME DEFAULT GETDATE(),
FOREIGN KEY(DepTID) REFERENCES Department(DepartmentID)
)


INSERT INTO Department(DeptNmae)
VALUES('IT'),('HR'),('Sales')

SELECT * FROM Department

INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhilash',6500,1)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Narendra',8500,3)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhidunnisha',7500,2)

SELECT * FROM Department
SELECT * FROM EMP

DELETE FROM Department
WHERE DepartmentID=3


UPDATE EMP
SET DepTID=2
WHERE EMPID=11



/*
With ALter Statement
*/

DROP TABLE [dbo].[Department]
DROP TABLE [dbo].[EMP]

--- NOT NULL
DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT,
EMPName VARCHAR(100),
Salary MONEY
)


ALTER TABLE EMP
ALTER COLUMN EMPID INT NOT NULL

ALTER TABLE EMP
ADD DOB DATETIME 

ALTER TABLE EMP
ALTER COLUMN EMPName VARCHAR(50)

ALTER TABLE EMP
DROP COLUMN DOB 

--UNIQUE 
DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT,
EMPName VARCHAR(100),
Salary MONEY
)


ALTER TABLE EMP
ADD CONSTRAINT UQ_EMP_EMPID UNIQUE(EMPID)

--- PRIMAY KEY

DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT,
EMPName VARCHAR(100),
Salary MONEY
)

ALTER TABLE EMP
ALTER COLUMN EMPID INT NOT NULL

ALTER TABLE EMP
ADD CONSTRAINT PK_EMP_EMPID PRIMARY KEY (EMPID)

--DEFAULT
DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT,
EMPName VARCHAR(100),
Salary MONEY
)

ALTER TABLE EMP
ADD InsertedDateTime DATETIME

ALTER TABLE EMP
ADD CONSTRAINT DF_EMP_InsertedDateTime DEFAULT GETDATE() FOR InsertedDateTime

---CHECK

DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT,
EMPName VARCHAR(100),
Salary MONEY
)

ALTER TABLE EMP
ADD CONSTRAINT CH_EMP_Salary CHECK (Salary>=10000)

--- FOREIGN KEY

CREATE TABLE Department
(
DepartmentID INT IDENTITY(1,1) PRIMARY KEY,
DeptNmae VARCHAR(50)
)

DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT IDENTITY(1,10),
EMPName VARCHAR(100) UNIQUE,
Salary MONEY CHECK (Salary>=5000),
DepTID INT,
InsertedDatetime DATETIME DEFAULT GETDATE()
)

ALTER TABLE EMP
ADD CONSTRAINT FK_DepTID_Department FOREIGN KEY (DepTID) REFERENCES Department(DepartmentID)

INSERT INTO Department(DeptNmae)
VALUES('IT'),('HR'),('Sales')
INSERT INTO Department(DeptNmae)
VALUES('Finance')


SELECT * FROM Department

INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhilash',6500,1)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Narendra',8500,3)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhidunnisha',7500,2)

SELECT * FROM Department
SELECT * FROM EMP


DELETE FROM Department 
WHERE DepartmentID=3

DELETE FROM Department 
WHERE DepartmentID=4

UPDATE Department
SET DepartmentID=30
WHERE DepartmentID=3

DROP TABLE IF EXISTS Department
CREATE TABLE Department
(
DepartmentID INT IDENTITY(1,1),
DeptNmae VARCHAR(50)
)

DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT IDENTITY(1,10),
EMPName VARCHAR(100) UNIQUE,
Salary MONEY CHECK (Salary>=5000),
DepTID INT,
InsertedDatetime DATETIME DEFAULT GETDATE()
)

ALTER TABLE EMP
ADD CONSTRAINT FK_DepTID_Department FOREIGN KEY (DepTID) REFERENCES Department(DepartmentID)

ALTER TABLE Department
ADD CONSTRAINT UQ_Department_DepartmentID UNIQUE (DepartmentID)


/*
Foreign Key Rules Or Casceding Rules
*/

DROP TABLE IF EXISTS Department
CREATE TABLE Department
(
DepartmentID INT  PRIMARY KEY,
DeptNmae VARCHAR(50)
)

DROP TABLE IF EXISTS EMP
CREATE TABLE EMP
(
EMPID INT IDENTITY(1,10),
EMPName VARCHAR(100) UNIQUE,
Salary MONEY CHECK (Salary>=5000),
DepTID INT,
InsertedDatetime DATETIME DEFAULT GETDATE()
)

ALTER TABLE EMP
ADD CONSTRAINT FK_DepTID_Department FOREIGN KEY (DepTID) REFERENCES Department(DepartmentID) 
ON UPDATE CASCADE

INSERT INTO Department(DepartmentID,DeptNmae)
VALUES(1,'IT'),(2,'HR'),(3,'Sales')
INSERT INTO Department(DepartmentID,DeptNmae)
VALUES(4,'Finance')


SELECT * FROM Department

INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhilash',6500,1)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Narendra',8500,3)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhidunnisha',7500,2)

SELECT * FROM Department
SELECT * FROM EMP


UPDATE Department
SET DepartmentID=30
WHERE DepartmentID=3

ALTER TABLE EMP
DROP CONSTRAINT FK_DepTID_Department


ALTER TABLE EMP
ADD CONSTRAINT FK_DepTID_Department FOREIGN KEY (DepTID) REFERENCES Department(DepartmentID) 
ON UPDATE CASCADE ON DELETE CASCADE

SELECT * FROM Department
SELECT * FROM EMP

DELETE FROM Department
WHERE DepartmentID=30


--SET NULL
TRUNCATE TABLE EMP
DELETE FROM Department

INSERT INTO Department(DepartmentID,DeptNmae)
VALUES(1,'IT'),(2,'HR'),(3,'Sales')
INSERT INTO Department(DepartmentID,DeptNmae)
VALUES(4,'Finance')


SELECT * FROM Department

INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhilash',6500,1)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Narendra',8500,3)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhidunnisha',7500,2)

ALTER TABLE EMP
DROP CONSTRAINT FK_DepTID_Department


ALTER TABLE EMP
ADD CONSTRAINT FK_DepTID_Department FOREIGN KEY (DepTID) REFERENCES Department(DepartmentID) 
ON UPDATE SET NULL ON DELETE SET NULL

SELECT * FROM Department
SELECT * FROM EMP

UPDATE Department
SET DepartmentID=30
WHERE DepartmentID=3

DELETE FROM Department
WHERE DepartmentID=1


--- SET DEFAULT

INSERT INTO Department(DepartmentID,DeptNmae)
VALUES(1,'IT'),(2,'HR'),(3,'Sales')
INSERT INTO Department(DepartmentID,DeptNmae)
VALUES(4,'Finance')

INSERT INTO Department(DepartmentID,DeptNmae)
VALUES(5,'NA')


SELECT * FROM Department

INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhilash',6500,1)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Narendra',8500,3)
INSERT INTO EMP(EMPName,Salary,DepTID)
VALUES('Abhidunnisha',7500,2)


SELECT * FROM Department
SELECT * FROM EMP

ALTER TABLE EMP
ADD CONSTRAINT DF_DepTID_EMP DEFAULT 5 FOR DepTID

ALTER TABLE EMP
DROP CONSTRAINT FK_DepTID_Department


ALTER TABLE EMP
ADD CONSTRAINT FK_DepTID_Department FOREIGN KEY (DepTID) REFERENCES Department(DepartmentID) 
ON UPDATE SET DEFAULT ON DELETE SET DEFAULT



SELECT * FROM Department
SELECT * FROM EMP

UPDATE Department
SET DepartmentID=10
WHERE DepartmentID=1


DELETE FROM Department
WHERE DepartmentID=3
