/*
System Objects
*/
SELECT * FROM sys.objects
SELECT * FROM sys.tables
SELECT * FROM sys.all_columns
SELECT * FROM sys.views
SELECT * FROM sys.Procedures


	SP_HELP
	SP_HELPTEXT
	SP_TABLES
	SP_COLUMNS
	SP_STORED_PROCEDURES

SP_HELP '[Person].[Address]'
SP_HELPTEXT '[dbo].[uspGetBillOfMaterials]'
SP_TABLES 'Per%'

SP_TABLES '%Customer%'

SP_COLUMNS 'Product'

SP_STORED_PROCEDURES '%Get%'

SP_STORED_PROCEDURES '%Sales%'

SELECT 	* FROM INFORMATION_SCHEMA.TABLES
SELECT 	* FROM INFORMATION_SCHEMA.COLUMNS
SELECT 	* FROM INFORMATION_SCHEMA.ROUTINES
SELECT 	* FROM INFORMATION_SCHEMA.VIEWS
SELECT 	* FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS

SELECT 	* FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='SalesTerritory'

